
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/Dockerfile to edit this template

FROM openjdk:8-alpine
MAINTAINER Grippo_Miguel
COPY target/portfolio-dock-img.jar api.jar
ENTRYPOINT ["java","-jar","/api.jar"]
